### ISSUE TITLE
模型生成能力？

### ISSUE THREAD

**Issue by zhoucz97** [TsinghuaAI/CPM-Distill#1]
这个蒸馏模型的生成能力这么差吗
复制一下我试的case：
以下是用CPM-1-Generate那个repo加载这个模型产生的结果：
```
Context: 美国的首都是华盛顿，日本的首都是东京，中国的首都是
CPM: 南京，山东的省会也是山东，墨西哥的首都是墨西哥，法国的首都是法国......（后面还有一串离谱的）
```

```
Context: 1+1=
CPM: 29000000000000000000000000000000000000000000000000.........
```

```
Context: 问题：1+1等于几？答案：
CPM: 1/3/6/8。

是不是有点太离谱了。。。

**Comment by t1101675** [comment]
您好，现在 CPM-Generate 的仓库主要适用于长文本生成，如果您要在 in context learning 的场景进行尝试，需要做两个改动。
1. 将原来的采样解码改成 greedy (argmax) 解码。
2. 设定分隔符，以对答案进行截断。例如，在您第一个例子里面，逗号是分隔符，那么就应该将模型生成的第一个逗号后面的内容截断掉，即CPM 生成“南京，”后面的内容都是没有意义的，这样才是 in context learning 的设定。

对于模型生成的正确性，我们在进行了上述修改之后尝试了一下您给的例子：
对于第一个例子，只要改变前面的 sample，例如输入以下 prompt ，都可以生成正确的结果。其原因可能是“东京”、“日本”、“南京”之间有一些共现的 bias，同时也说明设计 prompt 的重要性。

```
日本的首都是东京，美国的首都是华盛顿，中国的首都是
美国的首都是华盛顿，法国的首都是巴黎，中国的首都是
美国的首都是华盛顿，中国的首都是
美国的首都是华盛顿，中国的首都是
法国的首都是巴黎，中国的首都是

美国的首都是华盛顿，日本的首都是东京，法国的首都是
美国的首都是华盛顿，法国的首都是

美国的首都是华盛顿，日本的首都是
美国的首都是华盛顿，中国的首都是北京，日本的首都是
中国的首都是北京，美国的首都是华盛顿，日本的首都是
中国的首都是北京，日本的首都是
```

对于第二个例子，按照上述修改后模型能给出正确答案
```
Context: 1+1=

CPM: 2,
```

对于第三个例子，由于 prompt 形式太复杂，所以模型比较难做对。如果想按这个方式做的话，可以试试多拼几个样本

**Comment by zhoucz97** [comment]
确实发现了CPM-generate偏向于长文本生成，后面会按照您所说的改动一下代码试试看，非常感谢回复~~

**Comment by zhoucz97** [comment]
您好，还有一个问题想问一下，就是我用单机两卡的时候，在v100上没问题，但是在A100上会出现如下错误：
```
Traceback (most recent call last):                                                                                                                        
  File "finetune_lm.py", line 330, in <module>                                                                                                            
    main()                                                                                                                                                
  File "finetune_lm.py", line 256, in main                                                                                                                
    model.backward(loss)                                                                                                                                  
  File "/root/paddlejob/workspace/env_run/deepspeed/runtime/engine.py", line 1027, in backward                                                            
    loss.backward()                                                                                                                                       
  File "/usr/local/lib/python3.7/dist-packages/torch/tensor.py", line 221, in backward                                                                    
    torch.autograd.backward(self, gradient, retain_graph, create_graph)                                                                                   
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 132, in backward                                                         
    allow_unreachable=True)  # allow_unreachable flag                                                                                                     
RuntimeError: CUDA error: no kernel image is available for execution on the device 
```
也在A100上跑过其他的代码，是没有问题的。
请问您知道这是怎么回事吗？

**Comment by t1101675** [comment]
您好，可能是 torch 和 cuda 版本不匹配造成的，应该是 torch 的版本太高，但是用了比较低的 cuda 版本，在 A100 上造成了这个问题

**Comment by zhoucz97** [comment]
> 
已解决，cuda和torch版本都是匹配的，又重装了deepspeed和apex，可能是这俩个包的问题，谢谢回复~~
